# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' BS tree algorithm
#' 
#' @param y a numeric vector
#' @export
bs_tree <- function(y) {
    .Call('_SRAT_bs_tree', PACKAGE = 'SRAT', y)
}

num_sum <- function(eta, y, u, v, TREE) {
    .Call('_SRAT_num_sum', PACKAGE = 'SRAT', eta, y, u, v, TREE)
}

den_sum <- function(y, u, v) {
    .Call('_SRAT_den_sum', PACKAGE = 'SRAT', y, u, v)
}

obj_fun <- function(coef, Z, y, u, v, tree) {
    .Call('_SRAT_obj_fun', PACKAGE = 'SRAT', coef, Z, y, u, v, tree)
}

rowvec_norm <- function(x, p) {
    .Call('_SRAT_rowvec_norm', PACKAGE = 'SRAT', x, p)
}

obj_try <- function(M, idx, ndim, p, fac, Z, y, u, v, tree) {
    .Call('_SRAT_obj_try', PACKAGE = 'SRAT', M, idx, ndim, p, fac, Z, y, u, v, tree)
}

obj_min <- function(coef, Z, y, u, v, tree, nrep, ftol, nfun_max) {
    .Call('_SRAT_obj_min', PACKAGE = 'SRAT', coef, Z, y, u, v, tree, nrep, ftol, nfun_max)
}

sum_I <- function(y, w) {
    .Call('_SRAT_sum_I', PACKAGE = 'SRAT', y, w)
}

rank_res <- function(Y, D, V, eta, h) {
    .Call('_SRAT_rank_res', PACKAGE = 'SRAT', Y, D, V, eta, h)
}

f0 <- function(x, lambda, q) {
    .Call('_SRAT_f0', PACKAGE = 'SRAT', x, lambda, q)
}

f1 <- function(x, lambda) {
    .Call('_SRAT_f1', PACKAGE = 'SRAT', x, lambda)
}

hybrid <- function(q, lambda, tol, maxit) {
    .Call('_SRAT_hybrid', PACKAGE = 'SRAT', q, lambda, tol, maxit)
}

